"""
Firefox profile management for kitsune.
Handles profile creation, user.js injection, userChrome.css styling, and database cleanup.
"""

import os
import glob
import sqlite3
import configparser
from pathlib import Path


def get_firefox_dir() -> Path:
    """Returns the primary Firefox configuration directory."""
    candidates = [
        Path.home() / ".mozilla" / "firefox",
        Path.home() / "snap" / "firefox" / "common" / ".mozilla" / "firefox",
        Path.home() / ".var" / "app" / "org.mozilla.firefox" / ".mozilla" / "firefox",
    ]
    for c in candidates:
        if c.exists():
            return c
    return candidates[0]


def get_main_profile_path() -> Path:
    """Finds the user's default/main daily browsing profile."""
    ff_dir = get_firefox_dir()
    profiles_ini = ff_dir / "profiles.ini"
    
    if profiles_ini.exists():
        config = configparser.ConfigParser()
        config.read(str(profiles_ini))
        
        # Check install default section first
        for section in config.sections():
            if section.startswith("Install") and "Default" in config[section]:
                target = ff_dir / config[section]["Default"]
                if target.exists() and "kitsune" not in target.name:
                    return target
                    
        # Check default profile
        for section in config.sections():
            if section.startswith("Profile") and config[section].get("Default") == "1":
                rel = config[section].get("Path", "")
                target = ff_dir / rel
                if target.exists() and "kitsune" not in target.name:
                    return target

    # Fallback to any non-kitsune default-release profile
    for d in ff_dir.glob("*.default-release"):
        if "kitsune" not in d.name:
            return d

    for d in ff_dir.glob("*.default"):
        if "kitsune" not in d.name:
            return d

    return ff_dir


def create_kitsune_profile(slug: str, url: str, hide_browser_ui: bool = True) -> Path:
    """
    Creates an isolated Firefox profile folder for the web app with optimized settings.
    """
    ff_dir = get_firefox_dir()
    profile_dir = ff_dir / f"kitsune-{slug}"
    profile_dir.mkdir(parents=True, exist_ok=True)
    
    # 1. Write user.js with aggressive first-run overrides
    user_js = profile_dir / "user.js"
    user_js_content = [
        "// Auto-generated by kitsune",
        'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);',
        'user_pref("browser.tabs.inTitlebar", 0);',
        f'user_pref("browser.startup.homepage", "{url}");',
        'user_pref("browser.startup.page", 1);',
        'user_pref("browser.startup.firstrunSkipsHomepage", false);',
        'user_pref("browser.startup.homepage_override.mstone", "ignore");',
        'user_pref("startup.homepage_welcome_url", "");',
        'user_pref("startup.homepage_welcome_url.additional", "");',
        'user_pref("startup.homepage_override_url", "");',
        'user_pref("browser.newtabpage.enabled", false);',
        'user_pref("identity.fxaccounts.enabled", false);',
        'user_pref("browser.aboutwelcome.enabled", false);',
        'user_pref("trailhead.firstrun.branches", "nofirstrun-empty");',
        'user_pref("browser.sessionstore.resume_from_crash", false);',
        'user_pref("browser.sessionstore.resume_session_once", false);',
        'user_pref("browser.sessionstore.max_tabs_undo", 0);',
        'user_pref("browser.sessionstore.restore_pinned_tabs_on_demand", false);',
        'user_pref("browser.shell.checkDefaultBrowser", false);',
        'user_pref("dom.disable_open_during_load", false);',
        'user_pref("dom.allow_scripts_to_close_windows", true);',
        'user_pref("dom.storage_access.enabled", true);',
        'user_pref("dom.storage_access.auto_grant", true);',
        'user_pref("privacy.firstparty.isolate", false);',
        'user_pref("privacy.trackingprotection.enabled", false);',
        'user_pref("privacy.trackingprotection.socialtracking.enabled", false);',
        'user_pref("privacy.partition.always_partition_third_party_non_cookie_storage", false);',
        'user_pref("privacy.partition.serviceWorkers", false);',
        'user_pref("network.cookie.cookieBehavior", 0);',
        'user_pref("media.eme.enabled", true);',
        'user_pref("media.gmp-widevinecdm.enabled", true);',
        'user_pref("media.gmp-widevinecdm.visible", true);',
        'user_pref("media.autoplay.default", 0);',
        'user_pref("media.navigator.permission.disabled", false);',
        'user_pref("dom.events.asyncClipboard.readText", true);',
        'user_pref("dom.events.asyncClipboard.clipboardItem", true);',
        'user_pref("security.webauth.webauthn", true);',
        'user_pref("gfx.webrender.all", true);',
        'user_pref("extensions.autoDisableScopes", 0);',
        'user_pref("extensions.enabledScopes", 15);',
        'user_pref("xpinstall.signatures.required", false);',
    ]
    with open(user_js, "w", encoding="utf-8") as f:
        f.write("\n".join(user_js_content) + "\n")

    # 2. Write userChrome.css for clean app-like UI without breaking popup anchors
    if hide_browser_ui:
        chrome_dir = profile_dir / "chrome"
        chrome_dir.mkdir(parents=True, exist_ok=True)
        user_chrome_css = chrome_dir / "userChrome.css"
        css_content = """/* Clean App-Like Interface generated by kitsune */

/* Hide Tab Bar */
#TabsToolbar {
    visibility: collapse !important;
}

/* Hide URL bar, search bar, and address bar elements completely */
#nav-bar-customization-target,
#urlbar-container,
#urlbar,
#urlbar-input,
#identity-box,
#tracking-protection-icon-container,
#page-action-buttons {
    display: none !important;
    visibility: hidden !important;
}

/* Visually collapse Navigation/URL bar without breaking popup anchors */
#nav-bar {
    height: 0px !important;
    min-height: 0px !important;
    max-height: 0px !important;
    margin: 0px !important;
    padding: 0px !important;
    border: none !important;
    background: transparent !important;
    overflow: visible !important;
}

#nav-bar > * {
    opacity: 0 !important;
    pointer-events: none !important;
}

/* Keep permission prompts, notification popups, and menus fully visible and interactive */
#permission-popup,
#notification-popup,
#contentAreaContextMenu,
.popup-anchor,
panel[type="autocomplete-richlistbox"],
panel,
menupopup {
    visibility: visible !important;
    opacity: 1 !important;
    pointer-events: auto !important;
}

/* Hide Bookmarks Toolbar */
#PersonalToolbar {
    visibility: collapse !important;
}

/* Hide Sidebar Header */
#sidebar-header {
    display: none !important;
}
"""
        with open(user_chrome_css, "w", encoding="utf-8") as f:
            f.write(css_content)

    # 3. Clean up SQLite Profile Groups if present (to avoid duplicate title modifiers)
    clean_profile_groups_db(profile_dir.name)

    return profile_dir


def clean_profile_groups_db(profile_folder_name: str) -> None:
    """
    Cleans up any profile name recorded in Firefox's Profile Groups SQLite database
    so the window title doesn't display duplicate profile name tags.
    """
    ff_dir = get_firefox_dir()
    db_files = list((ff_dir / "Profile Groups").glob("*.sqlite")) if (ff_dir / "Profile Groups").exists() else []
    for db_path in db_files:
        try:
            conn = sqlite3.connect(str(db_path))
            cur = conn.cursor()
            cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='Profiles'")
            if cur.fetchone():
                cur.execute("UPDATE Profiles SET name = '' WHERE path = ?", (profile_folder_name,))
                conn.commit()
            conn.close()
        except Exception:
            pass
