"""
Profile and configuration management for kitsune across Gecko and Chromium engines on Linux and Windows.
"""

import configparser
import os
import sqlite3
import sys
from pathlib import Path


def is_windows() -> bool:
    return sys.platform == "win32"


def get_firefox_dir() -> Path:
    """Returns the primary Firefox configuration directory."""
    if is_windows():
        appdata = os.environ.get("APPDATA")
        if appdata:
            return Path(appdata) / "Mozilla" / "Firefox"
        return Path.home() / "AppData" / "Roaming" / "Mozilla" / "Firefox"

    candidates = [
        Path.home() / ".mozilla" / "firefox",
        Path.home() / "snap" / "firefox" / "common" / ".mozilla" / "firefox",
        Path.home() / ".var" / "app" / "org.mozilla.firefox" / ".mozilla" / "firefox",
    ]
    for c in candidates:
        if c.exists():
            return c
    return candidates[0]


def get_main_profile_path() -> Path:
    """Finds the user's default/main daily browsing profile."""
    ff_dir = get_firefox_dir()
    profiles_ini = ff_dir / "profiles.ini"

    if profiles_ini.exists():
        config = configparser.ConfigParser()
        try:
            config.read(str(profiles_ini))
            # Check install default section first
            for section in config.sections():
                if section.startswith("Install") and "Default" in config[section]:
                    target = ff_dir / config[section]["Default"]
                    if target.exists() and "kitsune" not in target.name:
                        return target

            # Check default profile
            for section in config.sections():
                if section.startswith("Profile") and config[section].get("Default") == "1":
                    rel = config[section].get("Path", "")
                    target = ff_dir / rel
                    if target.exists() and "kitsune" not in target.name:
                        return target
        except Exception:
            pass

    # Fallback to any non-kitsune default-release profile
    for d in ff_dir.glob("*.default-release"):
        if "kitsune" not in d.name:
            return d

    for d in ff_dir.glob("*.default"):
        if "kitsune" not in d.name:
            return d

    return ff_dir


def get_profile_dir(slug: str, browser_type: str = "gecko") -> Path:
    """Returns the isolated profile path for a web app based on its engine."""
    if browser_type == "chromium":
        if is_windows():
            base = Path(os.environ.get("APPDATA", Path.home())) / "kitsune" / "profiles"
        else:
            base = Path.home() / ".config" / "kitsune" / "profiles"
        p = base / f"kitsune-{slug}"
        p.mkdir(parents=True, exist_ok=True)
        return p

    # Gecko (Firefox/Zen/LibreWolf)
    ff_dir = get_firefox_dir()
    p = ff_dir / f"kitsune-{slug}"
    p.mkdir(parents=True, exist_ok=True)
    return p


def create_kitsune_profile(
    slug: str,
    url: str,
    browser_type: str = "gecko",
    hide_browser_ui: bool = True
) -> Path:
    """
    Creates an isolated profile directory for the web app.
    For Gecko engines, writes user.js, userChrome.css, and cleans SQLite name modifiers.
    For Chromium engines, initializes the user data directory.
    """
    profile_dir = get_profile_dir(slug, browser_type)

    if browser_type == "chromium":
        # Chromium manages profile state via --user-data-dir natively
        return profile_dir

    # 1. Write user.js with aggressive first-run overrides for Gecko
    user_js = profile_dir / "user.js"
    user_js_content = [
        "// Auto-generated by kitsune",
        'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);',
        'user_pref("browser.tabs.inTitlebar", 0);',
        f'user_pref("browser.startup.homepage", "{url}");',
        'user_pref("browser.startup.page", 1);',
        'user_pref("browser.startup.firstrunSkipsHomepage", false);',
        'user_pref("browser.startup.homepage_override.mstone", "ignore");',
        'user_pref("startup.homepage_welcome_url", "");',
        'user_pref("startup.homepage_welcome_url.additional", "");',
        'user_pref("startup.homepage_override_url", "");',
        'user_pref("browser.newtabpage.enabled", false);',
        'user_pref("identity.fxaccounts.enabled", false);',
        'user_pref("browser.aboutwelcome.enabled", false);',
        'user_pref("trailhead.firstrun.branches", "nofirstrun-empty");',
        'user_pref("browser.sessionstore.resume_from_crash", false);',
        'user_pref("browser.sessionstore.resume_session_once", false);',
        'user_pref("browser.sessionstore.max_tabs_undo", 0);',
        'user_pref("browser.sessionstore.restore_pinned_tabs_on_demand", false);',
        'user_pref("browser.shell.checkDefaultBrowser", false);',
        'user_pref("extensions.autoDisableScopes", 0);',
    ]
    with open(user_js, "w", encoding="utf-8") as f:
        f.write("\n".join(user_js_content) + "\n")

    # 2. Write userChrome.css for clean app-like UI without breaking popup anchors
    if hide_browser_ui:
        chrome_dir = profile_dir / "chrome"
        chrome_dir.mkdir(parents=True, exist_ok=True)
        user_chrome_css = chrome_dir / "userChrome.css"
        css_content = """/* Clean App-Like Interface generated by kitsune */

/* Hide Tab Bar */
#TabsToolbar {
    visibility: collapse !important;
}

/* Visually collapse Navigation/URL bar without breaking popup anchors */
#nav-bar {
    height: 0px !important;
    min-height: 0px !important;
    max-height: 0px !important;
    margin: 0px !important;
    padding: 0px !important;
    border: none !important;
    background: transparent !important;
    overflow: visible !important;
}

#nav-bar > * {
    opacity: 0 !important;
    pointer-events: none !important;
}

/* Keep permission prompts, notification popups, and menus fully visible and interactive */
#permission-popup,
#notification-popup,
#contentAreaContextMenu,
.popup-anchor,
panel[type="autocomplete-richlistbox"],
panel,
menupopup {
    visibility: visible !important;
    opacity: 1 !important;
    pointer-events: auto !important;
}

/* Hide Bookmarks Toolbar */
#PersonalToolbar {
    visibility: collapse !important;
}

/* Hide Sidebar Header */
#sidebar-header {
    display: none !important;
}
"""
        with open(user_chrome_css, "w", encoding="utf-8") as f:
            f.write(css_content)

    # 3. Clean up SQLite Profile Groups if present
    clean_profile_groups_db(profile_dir.name)

    return profile_dir


def clean_profile_groups_db(profile_folder_name: str) -> None:
    """
    Cleans up any profile name recorded in Firefox's Profile Groups SQLite database.
    """
    ff_dir = get_firefox_dir()
    db_files = list((ff_dir / "Profile Groups").glob("*.sqlite")) if (ff_dir / "Profile Groups").exists() else []
    for db_path in db_files:
        try:
            conn = sqlite3.connect(str(db_path))
            cur = conn.cursor()
            cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='Profiles'")
            if cur.fetchone():
                cur.execute("UPDATE Profiles SET name = '' WHERE path = ?", (profile_folder_name,))
                conn.commit()
            conn.close()
        except Exception:
            pass
